### ISSUE TITLE
Error when trying to talk to Snowflake

### ISSUE THREAD

**Issue by wx-yz** [ballerina-platform/module-ballerinax-snowflake#41]
**Description:**
I'm trying to connect to Snowflake and get some data. My Ballerina code,

```
import ballerina/http;
import ballerina/io;
import ballerina/sql;
import ballerinax/snowflake;      
import ballerinax/snowflake.driver as _;  

configurable string account_identifier = ?;
configurable string user = ?;
configurable string password = ?;
snowflake:Options options = {
    requestGeneratedKeys: snowflake:NONE  
};
snowflake:Client snowflakeClient = check new (account_identifier, user, password, options);

type Customer record {
    int id;
    string name;
    string address;
    string phone;
    string account_balance;
    string comment;
};

service / on new http:Listener(9090) {    
    resource function get customers() returns Customer[]|error {
        sql:ParameterizedQuery sqlQuery = `SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 10`;
        stream<record {}, error?> resultStream = snowflakeClient->query(sqlQuery);
        Customer[] result = [];
        check from record{} customer in resultStream
        do {
            result.push(<Customer>customer);
            io:println("Full details of customer: ", result);
        };
        return result;
    }
}
```

I'm using the Snowflake same data set.

When I do GET /customers I'm seeing following exception at the server side,

```
java.lang.RuntimeException: Failed to initialize MemoryUtil. Was Java started with `--add-opens=java.base/java.nio=ALL-UNNAMED`? (See https://arrow.apache.org/docs/java/install.html)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:146)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:231)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:226)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:728)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:67)
	at net.snowflake.client.jdbc.internal.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:145)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.setFirstChunkRowCountForArrow(SnowflakeResultSetSerializableV1.java:1127)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:601)
	at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:497)
	at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:34)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:234)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:140)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:776)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:684)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:267)
	at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:122)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at io.ballerina.stdlib.sql.nativeimpl.QueryProcessor.nativeQueryExecutable(QueryProcessor.java:121)
	at io.ballerina.stdlib.sql.nativeimpl.QueryProcessor.lambda$nativeQuery$0(QueryProcessor.java:88)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @6923aa49
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:91)
	... 23 more
time=2024-03-17T16:54:03.789-07:00 level=ERROR module=ballerina/http message="unhandled error returned from the service" error={"causes":[],"message":"Error while executing SQL query: SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER LIMIT 10. JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:231)..","detail":{"errorCode":200001,"sqlState":"XX000"},"stackTrace":[]} path="/customers" method="GET"
```

I'm using following
```
% bal --version
Ballerina 2201.8.6 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2

% java --version
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode)
```

Appreciate any help to figure out what I'm doing wrong. Thanks.
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by daneshk** [comment]
Snowflake driver fails with Java 16 and above because starting with JDK 16, strong encapsulation was turned on by default and one of the driver dependencies has employed the use of sun.misc.Unsafe along with reflection. This is not allowed in Java 16 and above. Therefore, to run the program, you need to use Java 15 or below. For more information, see [here](https://community.snowflake.com/s/article/JDBC-Driver-Compatibility-Issue-With-JDK-16-and-Later). If you are using Java 16 or above, you can use the following workaround to work with the Snowflake connector:

* Export the following environment variable:
```
export JDK_JAVA_OPTIONS="--add-opens java.base/java.nio=ALL-UNNAMED"
```
* Set Snowflake property JDBC_QUERY_RESULT_FORMAT to JSON as follows:
```
snowflake:Options options = {
    properties: {
        "JDBC_QUERY_RESULT_FORMAT": "JSON"
    }
};
```

**Comment by daneshk** [comment]
Closing the issue based on the above comment. Please reopen if you still find the issue.
